# Generated by Django 4.2.2 on 2023-06-12 12:55

import chat.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.SlugField(max_length=20)),
                ('group_info', models.CharField(blank=True, max_length=300, null=True)),
                ('creater', models.ForeignKey(on_delete=models.SET(chat.models.get_sentinal_user), to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='all_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.group')),
                ('parent_user', models.ForeignKey(on_delete=models.SET(chat.models.get_sentinal_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
