# Generated by Django 4.2.2 on 2023-06-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile_groupprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
